# Numpy - Python Library

In [82]:
import numpy as np

In [83]:
mylist = [1,2,3]

In [84]:
np.array(mylist)

array([1, 2, 3])

In [85]:
mymatrix = [[1,2,3],[4,5,6],[7,8,9]]

In [86]:
mymatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [88]:
np.array(mymatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [92]:
np.zeros(4)

array([0., 0., 0., 0.])

In [93]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [94]:
np.ones(3)

array([1., 1., 1.])

In [95]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [96]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [97]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [98]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [99]:
np.random.rand(2)

array([0.09864725, 0.77647258])

In [100]:
np.random.rand(4,4)

array([[0.46456957, 0.22456419, 0.4017925 , 0.63656752],
       [0.15783069, 0.19421948, 0.65185988, 0.49257399],
       [0.0789617 , 0.30217519, 0.15434341, 0.7207709 ],
       [0.66716487, 0.62408124, 0.20509411, 0.54205463]])

In [101]:
np.random.randn(2)

array([ 1.69841001, -0.07705086])

In [102]:
np.random.randn(4,4)

array([[-1.64214756,  1.00401261,  0.21031505,  1.31283219],
       [-0.38880582,  2.85245589, -0.49579439, -0.18481656],
       [-0.14181746,  1.22852475, -0.14018694, -0.56804592],
       [ 0.04127223,  0.28970611,  0.07218938,  1.01931385]])

In [104]:
np.random.randint(1,100)

24

In [106]:
np.random.randint(0,100,10)

array([24, 23, 31, 53, 30, 89, 14, 70, 32, 93])

In [108]:
arr = np.arange(0,25)

In [109]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [114]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [115]:
arr.min()

0

In [116]:
arr.max()

24

In [117]:
arr.argmin()

0

In [118]:
arr2 = np.arange(5,25)

In [119]:
arr2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [121]:
arr2.min()

5

In [122]:
arr2.max()

24

In [123]:
arr2.argmin()

0

In [124]:
arr2.argmax()

19

In [125]:
arr2.shape

(20,)

In [128]:
arr2.reshape(5,4).shape

(5, 4)

In [129]:
arr2.dtype

dtype('int32')

In [130]:
arr3 = np.arange(10, 11.2)

In [131]:
arr3

array([10., 11.])

In [133]:
arr3.dtype

dtype('float64')

In [134]:
arr4 = np.arange(100,120)

In [135]:
arr4

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119])

In [137]:
arr4[2]

102

In [139]:
arr4[0:5]

array([100, 101, 102, 103, 104])

In [140]:
arr4[5:]

array([105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119])

In [142]:
arr4[0:5] = 10

In [143]:
arr4

array([ 10,  10,  10,  10,  10, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119])

In [144]:
arr5 = np.arange(200,220)

In [145]:
arr5

array([200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212,
       213, 214, 215, 216, 217, 218, 219])

In [146]:
arr5copy = arr.copy()

In [148]:
arr5copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [153]:
arr2d = np.array(([1,2,3],[4,5,6],[7,8,9]))

# arr2d

In [156]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [154]:
arr2d[1]

array([4, 5, 6])

In [155]:
arr2d[1,1]

5

In [157]:
arr2d[1,2]

6

In [158]:
arr2d[1:, 1:]

array([[5, 6],
       [8, 9]])

In [159]:
arr2d[:2, :2]

array([[1, 2],
       [4, 5]])

In [160]:
arr4

array([ 10,  10,  10,  10,  10, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119])

In [161]:
arr5

array([200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212,
       213, 214, 215, 216, 217, 218, 219])

In [162]:
arr5 > 205

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [166]:
arr6 = arr5 >205

In [167]:
arr6

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [170]:
arr5

array([200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212,
       213, 214, 215, 216, 217, 218, 219])

In [171]:
arr5 + arr5

array([400, 402, 404, 406, 408, 410, 412, 414, 416, 418, 420, 422, 424,
       426, 428, 430, 432, 434, 436, 438])

In [172]:
arr5 - arr5

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [173]:
arr5 /arr5

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [174]:
1/arr5

array([0.005     , 0.00497512, 0.0049505 , 0.00492611, 0.00490196,
       0.00487805, 0.00485437, 0.00483092, 0.00480769, 0.00478469,
       0.0047619 , 0.00473934, 0.00471698, 0.00469484, 0.0046729 ,
       0.00465116, 0.00462963, 0.00460829, 0.00458716, 0.00456621])

In [175]:
arr>5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [180]:
arr5

array([200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212,
       213, 214, 215, 216, 217, 218, 219])

In [187]:
 arr7 = arr5>205

In [192]:
arr5[arr7]

array([206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218,
       219])

In [193]:
mylist = range(10,20)

In [194]:
mylist

range(10, 20)

In [195]:
mylist(int(mylist)>15)

TypeError: int() argument must be a string, a bytes-like object or a number, not 'range'

In [200]:
arr27 = np.arange(10,13)

In [201]:
arr27

array([10, 11, 12])

In [210]:
arr28 = np.array([[1,2,3,4],[4,5,6,4],[7,8,9,4],[10,11,12,4]])

In [211]:
arr28

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  4],
       [ 7,  8,  9,  4],
       [10, 11, 12,  4]])

In [212]:
arr27 * arr28

ValueError: operands could not be broadcast together with shapes (3,) (4,4) 

In [213]:
arr29 = np.array([[0,0,0],[10,10,10],[20,20,20]])

In [214]:
arr30 = np.array([0,10,20,30])

In [215]:
arr30

array([ 0, 10, 20, 30])

In [230]:
arr30.reshape(4,1)

array([[ 0],
       [10],
       [20],
       [30]])

In [231]:
arr31 = np.arange(10,13)

In [232]:
arr32 = arr31.reshape(1,3)

In [233]:
arr32.shape

(1, 3)

In [234]:
arr30 * arr32

ValueError: operands could not be broadcast together with shapes (4,) (1,3) 

In [237]:
print("b")

b


In [224]:
arr30

array([ 0, 10, 20, 30])